server:
  port: 7005

eureka:
  instance:
    hostname: localhost  #eureka 服务端的服务名称、
  client:
    register-with-eureka: false # 表示eureka 不向注册中心注册自己
    fetch-registry: false # false 表示自己就是服务注册端，不需要去服务检索
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

